# File: docker-compose.yml
version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:latest
    container_name: todo-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  # Backend API
  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/todos
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  # Frontend React App
  frontend:
    build: ./frontend
    container_name: todo-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local